# Uncomment this line to define a global platform for your project
platform :ios, ’10.0’

target 'ValidApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

   pod 'Alamofire', '~> 4.5'
   pod 'AlamofireImage', '~> 3.3'
  # Pods for ValidApp

end
